# Generated by Django 2.1.3 on 2018-11-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bodey',
            new_name='body',
        ),
    ]
